language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t crazymilo/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true crazymilo/docker-react npm run test

